#:kivy 1.0

<Base>: 
    rows: 6
    columns: 1
    padding: 100
    spacing: 30
    orientation: 'vertical'
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'resources/images/light-green.jpg'
    Label:
        text: 'Digital Agriculture'
        font_size: 60
        font_name: 'resources/fonts/Orbitron-Bold.ttf'
        bold: True
        color: (240, 240, 240, 1)
        background_color: (240, 240, 240, 1)
    AnchorLayout:
        Button:
            text: 'Start'
            on_release: root.start_map()
            size_hint_x: 0.5
    AnchorLayout:
        Button:
            text: 'Instructions'
            size_hint_x: 0.5
    AnchorLayout:
        Button:
            text: 'Documentation'
            size_hint_x: 0.5
    AnchorLayout:
        Button:
            text: 'Project Information'
            size_hint_x: 0.5
